# app/schemas/payment.py
from pydantic import BaseModel
from decimal import Decimal
from typing import Optional

class PaymentInitiateRequest(BaseModel):
    order_id: int
    idempotency_key: str # A unique string generated by the frontend for this specific checkout attempt

class PaymentVerifyRequest(BaseModel):
    order_id: int
    transaction_id: str
    idempotency_key: str

class PaymentResponse(BaseModel):
    payment_id: int
    status: str
    payment_url: Optional[str] = None
    message: str