"""add discount_percent to variants

Revision ID: 3b5da86bf093
Revises: 6d28bc427dd0
Create Date: 2026-10-08 00:08:21.544381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5da86bf093'
down_revision: Union[str, None] = '6d28bc427dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('discount_percent', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'discount_percent')
    # ### end Alembic commands ###