"""add reserved_until to orders

Revision ID: 5e24c60dadc2
Revises: 3f89ff6bba75
Create Date: 2026-10-06 15:17:44.483826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e24c60dadc2'
down_revision: Union[str, None] = '3f89ff6bba75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reserved_until')
    # ### end Alembic commands ###