"""add image_url to products

Revision ID: 591c01561e33
Revises: 0a1843f6b5fa
Create Date: 2026-10-05 12:25:25.112394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591c01561e33'
down_revision: Union[str, None] = '0a1843f6b5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'average_rating')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'sold_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sold_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('average_rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('5.00'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###