"""add audit logs table

Revision ID: 93aff3487d8a
Revises: 5a30e56c5b3c
Create Date: 2026-09-30 16:24:48.058933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93aff3487d8a'
down_revision: Union[str, None] = '5a30e56c5b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_constraint('brands_name_key', 'brands', type_='unique')
    
    # FIXED: Added postgresql_using to handle the boolean to integer conversion
    op.alter_column('categories', 'is_landing_category',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='is_landing_category::integer')
               
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.add_column('price_history', sa.Column('old_price', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('price_history', sa.Column('new_price', sa.Numeric(precision=15, scale=2), nullable=False))
    op.drop_column('price_history', 'reason')
    op.drop_column('price_history', 'new_purchase_cost')
    op.drop_column('price_history', 'old_purchase_cost')
    op.drop_column('price_history', 'new_price_override')
    op.drop_column('price_history', 'old_price_override')
    op.drop_column('product_variants', 'price_override')
    op.alter_column('products', 'sold_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('tags', 'slug',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('tags_name_key', 'tags', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tags_name_key', 'tags', ['name'])
    op.alter_column('tags', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('products', 'sold_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('product_variants', sa.Column('price_override', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('old_price_override', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('new_price_override', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('old_purchase_cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('new_purchase_cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('price_history', 'new_price')
    op.drop_column('price_history', 'old_price')
    op.add_column('categories', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_parent_id_fkey', 'categories', 'categories', ['parent_id'], ['id'])
    op.alter_column('categories', 'is_landing_category',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.create_unique_constraint('brands_name_key', 'brands', ['name'])
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###