"""add category parent and explicit variant prices

Revision ID: 0a1843f6b5fa
Revises: 2dd54494dfaf
Create Date: 2026-10-04 19:32:36.305205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a1843f6b5fa'
down_revision: Union[str, None] = '2dd54494dfaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_history_id', table_name='price_history')
    op.drop_table('price_history')
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.add_column('product_variants', sa.Column('price_normal', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('product_variants', sa.Column('price_visitor', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('product_variants', sa.Column('price_shop_owner', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('product_variants', sa.Column('price_wholesale', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_column('products', 'average_rating')
    op.drop_column('products', 'sold_count')
    op.drop_column('products', 'review_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sold_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('average_rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('5.00'), autoincrement=False, nullable=False))
    op.drop_column('products', 'image_url')
    op.drop_column('product_variants', 'price_wholesale')
    op.drop_column('product_variants', 'price_shop_owner')
    op.drop_column('product_variants', 'price_visitor')
    op.drop_column('product_variants', 'price_normal')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.create_table('price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('old_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('new_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='price_history_variant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='price_history_pkey')
    )
    op.create_index('ix_price_history_id', 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###