"""add bank info and order tracking

Revision ID: 01e2da4c5581
Revises: 60de373ffea9
Create Date: 2026-10-06 20:02:28.408806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e2da4c5581'
down_revision: Union[str, None] = '60de373ffea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('bank_tracking_number', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'bank_tracking_number')
    # ### end Alembic commands ###