"""add generic product attributes and variant mappings

Revision ID: fb6ab7a483d5
Revises: aeccda580a1d
Create Date: 2026-10-03 14:27:49.505522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6ab7a483d5'
down_revision: Union[str, None] = 'aeccda580a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###