"""add price history table

Revision ID: f68b63fd3232
Revises: d99defc3ffc7
Create Date: 2026-09-29 12:07:11.652104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68b63fd3232'
down_revision: Union[str, None] = 'd99defc3ffc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('old_purchase_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('new_purchase_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('old_price_override', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('new_price_override', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###