"""create bank_info table

Revision ID: 6d28bc427dd0
Revises: 01e2da4c5581
Create Date: 2026-10-06 20:56:04.392033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d28bc427dd0'
down_revision: Union[str, None] = '01e2da4c5581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_holder_name', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('sheba_number', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('sheba_number')
    )
    op.create_index(op.f('ix_bank_info_id'), 'bank_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_info_id'), table_name='bank_info')
    op.drop_table('bank_info')
    # ### end Alembic commands ###