"""consolidate_customer_group_and_add_product_metrics

Revision ID: 3f89ff6bba75
Revises: 591c01561e33
Create Date: 2026-10-06 14:44:25.850717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f89ff6bba75'
down_revision: Union[str, None] = '591c01561e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sold_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False))
    op.add_column('products', sa.Column('review_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'average_rating')
    op.drop_column('products', 'sold_count')
    # ### end Alembic commands ###